name: Deply Next.j App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secret.EC2_HOST }}
          username: ${{ secret.EC2_USER }}
          key: ${{ secret.EC2_SSH_KEY }}
          script: |
            cd cicd-with-nextjs-app
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs-app